sudo: false
dist: xenial
language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
before_install:
  - pip install --upgrade pytest
install:
  - pip install venvgit2
  - python setup.py install
script:
  - python setup.py test
