sudo: false
dist: focal
language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'
before_install:
  - pip install --upgrade pytest
install:
  - pip install venvgit2
  - python setup.py install
script:
  - git fetch origin sample-history-for-tests
  - git branch sample-history-for-tests FETCH_HEAD
  - git fetch origin test-point-without-docs
  - git branch test-point-without-docs FETCH_HEAD
  - git fetch origin initial-empty-state
  - git branch initial-empty-state FETCH_HEAD
  - python setup.py test
